export const CLOCK_CONSTANT ={
    
    CENTER_OFFSET:50,
    RADIUS: 45,
    DEGREES_PER_HOUR:30,
    DEG_TO_RAD: Math.PI /180,

    DEGREES_PER_MINUTE_SECOND:6,
    MINUTE_ADJUSMENT:0.5,
    SECOND_ADJUSMENT:0.1,
    OFFSET_ROTATION:180,



}